### ISSUE TITLE
User playlists are not supported

### ISSUE THREAD

**Issue by Wayneoween** [gju/porygon2-spotify#2]
**Current Behaviour**
When posting an URI to a _public_ playlist from a certain user, the bot does not output anything.

**Expected Behaviour**
Bot shows info about the playlist like it does with songs.

**Steps to Reproduce**
Send Album link to Channel: spotify:user:andreas.blixt:playlist:1itC2kKqIqun8OU05J5G8v

**Comment by gju** [comment]
Done.
